import { Category, Unit } from './types';

export interface PresetItem {
  id: string;
  category: Category;
  description: string;
  unit: Unit;
  defaultQuantity: number;
  materialUnitCost: number; // Custo médio de materiais
  laborUnitCost: number;    // Custo médio de mão de obra
  notes?: string;
}

export const PRESET_CATEGORIES: Category[] = [
  'Demolição e Estaleiro',
  'Alvenaria e Estruturas',
  'Pladur e Tetos Falsos',
  'Pinturas e Acabamentos',
  'Eletricidade e Iluminação',
  'Canalização e Sanitários',
  'Pavimentos e Revestimentos',
  'Carpintarias e Caixilharias',
  'Climatização e AVAC',
  'Isolamentos e Impermeabilização',
  'Outros Trabalhos',
];

export const PRESET_ITEMS: PresetItem[] = [
  // 1. Demolição e Estaleiro
  {
    id: 'dem-01',
    category: 'Demolição e Estaleiro',
    description: 'Demolição manual de paredes de alvenaria simples c/ ensacamento e limpeza',
    unit: 'm²',
    defaultQuantity: 20,
    materialUnitCost: 1.5,
    laborUnitCost: 14.0,
    notes: 'Inclui picagem e remoção até ao suporte limpo',
  },
  {
    id: 'dem-02',
    category: 'Demolição e Estaleiro',
    description: 'Levantamento de pavimento cerâmico ou mosaico existente c/ betonilha',
    unit: 'm²',
    defaultQuantity: 30,
    materialUnitCost: 1.0,
    laborUnitCost: 12.0,
    notes: 'Inclui acondicionamento de entulho',
  },
  {
    id: 'dem-03',
    category: 'Demolição e Estaleiro',
    description: 'Desmontagem e remoção de loiças sanitárias, banheira e torneiras existentes',
    unit: 'vg',
    defaultQuantity: 1,
    materialUnitCost: 0,
    laborUnitCost: 80.0,
    notes: 'Desconexão de redes e tamponamento provisório',
  },
  {
    id: 'dem-04',
    category: 'Demolição e Estaleiro',
    description: 'Aluguer e colocação de contentor de entulho (5m³) c/ transporte a vazadouro autorizado e taxas',
    unit: 'un',
    defaultQuantity: 2,
    materialUnitCost: 165.0,
    laborUnitCost: 25.0,
    notes: 'Com guias e certificado ambiental RCD',
  },
  {
    id: 'dem-05',
    category: 'Demolição e Estaleiro',
    description: 'Proteção geral de zonas de passagem, elevador, caixilharias e pavimentos com cartão e plástico',
    unit: 'vg',
    defaultQuantity: 1,
    materialUnitCost: 65.0,
    laborUnitCost: 85.0,
    notes: 'Montagem de estaleiro e proteção de partes comuns',
  },

  // 2. Alvenaria e Estruturas
  {
    id: 'alv-01',
    category: 'Alvenaria e Estruturas',
    description: 'Execução de parede em tijolo cerâmico 11cm assente com argamassa hidrófuga',
    unit: 'm²',
    defaultQuantity: 25,
    materialUnitCost: 12.5,
    laborUnitCost: 18.0,
    notes: 'Inclui amarrações metálicas aos pilares/vigas',
  },
  {
    id: 'alv-02',
    category: 'Alvenaria e Estruturas',
    description: 'Reboco desempenado tradicional em paredes interiores c/ argamassa de cimento e areia',
    unit: 'm²',
    defaultQuantity: 50,
    materialUnitCost: 6.5,
    laborUnitCost: 14.5,
    notes: 'Inclui mestras e arestas vivas',
  },
  {
    id: 'alv-03',
    category: 'Alvenaria e Estruturas',
    description: 'Execução de betonilha de regularização e enchimento de pavimento c/ espessura média 5cm',
    unit: 'm²',
    defaultQuantity: 40,
    materialUnitCost: 8.5,
    laborUnitCost: 11.5,
    notes: 'Acabamento desempenado pronto a receber acabamento final',
  },

  // 3. Pladur e Tetos Falsos
  {
    id: 'pla-01',
    category: 'Pladur e Tetos Falsos',
    description: 'Execução de teto falso em gesso cartonado (Pladur 13mm) c/ estrutura metálica e isolamento em lã mineral',
    unit: 'm²',
    defaultQuantity: 45,
    materialUnitCost: 16.0,
    laborUnitCost: 15.0,
    notes: 'Inclui fita armada e 3 passagens de massa de juntas Q3',
  },
  {
    id: 'pla-02',
    category: 'Pladur e Tetos Falsos',
    description: 'Execução de divisória em gesso cartonado duplo (placa dupla 13mm cada face) c/ isolamento acústico',
    unit: 'm²',
    defaultQuantity: 20,
    materialUnitCost: 26.0,
    laborUnitCost: 22.0,
    notes: 'Espessura final 100mm, isolamento em lã de rocha 50mm',
  },
  {
    id: 'pla-03',
    category: 'Pladur e Tetos Falsos',
    description: 'Execução de teto falso hidrófugo (placa verde) em zonas húmidas (WC / Cozinha)',
    unit: 'm²',
    defaultQuantity: 12,
    materialUnitCost: 18.5,
    laborUnitCost: 16.0,
    notes: 'Para resistência à humidade e vapores',
  },
  {
    id: 'pla-04',
    category: 'Pladur e Tetos Falsos',
    description: 'Execução de sanca de luz indireta para fita LED em gesso cartonado',
    unit: 'ml',
    defaultQuantity: 8,
    materialUnitCost: 12.0,
    laborUnitCost: 18.0,
    notes: 'Remate impecável pronto para pintura',
  },

  // 4. Pinturas e Acabamentos
  {
    id: 'pin-01',
    category: 'Pinturas e Acabamentos',
    description: 'Pintura geral de paredes interiores c/ 1 demão de primário e 2 demãos de tinta plástica lavável',
    unit: 'm²',
    defaultQuantity: 120,
    materialUnitCost: 3.8,
    laborUnitCost: 6.5,
    notes: 'Inclui isolamento de rodapés e caixilharias com fita crepe',
  },
  {
    id: 'pin-02',
    category: 'Pinturas e Acabamentos',
    description: 'Barragem completa de paredes e tetos c/ massa de acabamento fino para acabamento liso perfeito (Q4)',
    unit: 'm²',
    defaultQuantity: 80,
    materialUnitCost: 3.2,
    laborUnitCost: 7.5,
    notes: 'Inclui lixagem mecânica c/ aspiração sem pó',
  },
  {
    id: 'pin-03',
    category: 'Pinturas e Acabamentos',
    description: 'Pintura de tetos em tinta mate anti-reflexo branca anti-fungos',
    unit: 'm²',
    defaultQuantity: 60,
    materialUnitCost: 3.5,
    laborUnitCost: 6.0,
    notes: 'Duas demãos cruzadas',
  },
  {
    id: 'pin-04',
    category: 'Pinturas e Acabamentos',
    description: 'Tratamento e pintura de paredes exteriores c/ tinta de membrana elastomérica 100% acrílica',
    unit: 'm²',
    defaultQuantity: 70,
    materialUnitCost: 7.5,
    laborUnitCost: 9.5,
    notes: 'Resistente a intempéries e microfissuras',
  },

  // 5. Eletricidade e Iluminação
  {
    id: 'ele-01',
    category: 'Eletricidade e Iluminação',
    description: 'Ponto elétrico completo (tomada 2P+T ou interruptor) c/ abertura de roço, tubagem VD, cablagem e aparelhagem',
    unit: 'un',
    defaultQuantity: 24,
    materialUnitCost: 14.0,
    laborUnitCost: 22.0,
    notes: 'Aparelhagem série standard (ex: Efapel Logus90 ou Legrand)',
  },
  {
    id: 'ele-02',
    category: 'Eletricidade e Iluminação',
    description: 'Ponto de luz no teto c/ abertura em teto falso, cablagem e ligação de foco LED embutido',
    unit: 'un',
    defaultQuantity: 16,
    materialUnitCost: 12.0,
    laborUnitCost: 15.0,
    notes: 'Inclui foco LED redondo orientável 7W branco quente',
  },
  {
    id: 'ele-03',
    category: 'Eletricidade e Iluminação',
    description: 'Fornecimento e montagem de Quadro Elétrico Geral completo c/ disjuntores e diferenciais de proteção',
    unit: 'un',
    defaultQuantity: 1,
    materialUnitCost: 240.0,
    laborUnitCost: 160.0,
    notes: 'Conforme normas DGEG c/ barramentos e proteção contra sobretensões',
  },
  {
    id: 'ele-04',
    category: 'Eletricidade e Iluminação',
    description: 'Instalação de rede de dados (ITED) c/ tomada RJ45 Cat6 e cabo UTP',
    unit: 'un',
    defaultQuantity: 4,
    materialUnitCost: 16.0,
    laborUnitCost: 24.0,
    notes: 'Testado com certificador de rede',
  },

  // 6. Canalização e Sanitários
  {
    id: 'can-01',
    category: 'Canalização e Sanitários',
    description: 'Rede de abastecimento de águas fria/quente em tubo multicamada c/ isolamento térmico (ponto de água)',
    unit: 'un',
    defaultQuantity: 6,
    materialUnitCost: 28.0,
    laborUnitCost: 40.0,
    notes: 'Desde o coletor até à torneira de esquadria',
  },
  {
    id: 'can-02',
    category: 'Canalização e Sanitários',
    description: 'Rede de esgotos e ventilação primária em tubo PVC colado de alta resistência (ponto de esgoto)',
    unit: 'un',
    defaultQuantity: 5,
    materialUnitCost: 22.0,
    laborUnitCost: 35.0,
    notes: 'Inclui sifão ou ligação direta ao coletor principal',
  },
  {
    id: 'can-03',
    category: 'Canalização e Sanitários',
    description: 'Instalação de estrutura de autoclismo embutido (tipo Geberit Duofix) c/ placa de comando',
    unit: 'un',
    defaultQuantity: 1,
    materialUnitCost: 195.0,
    laborUnitCost: 75.0,
    notes: 'Para sanita suspensa',
  },
  {
    id: 'can-04',
    category: 'Canalização e Sanitários',
    description: 'Montagem de loiças sanitárias (sanita suspensa/chão, móvel de lavatório c/ espelho e torneiras)',
    unit: 'vg',
    defaultQuantity: 1,
    materialUnitCost: 45.0,
    laborUnitCost: 120.0,
    notes: 'Mão de obra de fixação, afinação e silicone anti-fungos',
  },
  {
    id: 'can-05',
    category: 'Canalização e Sanitários',
    description: 'Fornecimento e aplicação de base de duche em resina mineral extraplana c/ válvula de esgoto',
    unit: 'un',
    defaultQuantity: 1,
    materialUnitCost: 190.0,
    laborUnitCost: 65.0,
    notes: 'Assente sobre base nivelada c/ teste de estanquicidade',
  },

  // 7. Pavimentos e Revestimentos
  {
    id: 'pav-01',
    category: 'Pavimentos e Revestimentos',
    description: 'Assentamento de revestimento cerâmico/azulejo em paredes de WC/Cozinha c/ cimento-cola flexível C2TE',
    unit: 'm²',
    defaultQuantity: 35,
    materialUnitCost: 11.0,
    laborUnitCost: 19.0,
    notes: 'Não inclui cerâmico (ou considerar cerâmica fornecida pelo cliente). Inclui cola, cruzetas autonivelantes e betume',
  },
  {
    id: 'pav-02',
    category: 'Pavimentos e Revestimentos',
    description: 'Assentamento de pavimento cerâmico ou porcelânico retificado c/ corte e juntas retilíneas',
    unit: 'm²',
    defaultQuantity: 45,
    materialUnitCost: 12.5,
    laborUnitCost: 18.5,
    notes: 'Inclui colagem dupla e betumação hidro-repelente',
  },
  {
    id: 'pav-03',
    category: 'Pavimentos e Revestimentos',
    description: 'Fornecimento e colocação de piso flutuante laminado AC5 (8mm) c/ tela acústica de 2mm e rodapés lacados',
    unit: 'm²',
    defaultQuantity: 55,
    materialUnitCost: 19.5,
    laborUnitCost: 10.5,
    notes: 'Inclui perfis de transição e remate em portas',
  },
  {
    id: 'pav-04',
    category: 'Pavimentos e Revestimentos',
    description: 'Afagamento, calafetação e envernizamento de chão em madeira maciça / taco existente c/ 3 demãos de verniz PU',
    unit: 'm²',
    defaultQuantity: 40,
    materialUnitCost: 8.0,
    laborUnitCost: 16.0,
    notes: 'Verniz poliuretano base aquosa sem cheiro',
  },

  // 8. Carpintarias e Caixilharias
  {
    id: 'car-01',
    category: 'Carpintarias e Caixilharias',
    description: 'Fornecimento e montagem de porta interior lisa lacada a branco (c/ aro, guarnições, puxador e fechadura inox)',
    unit: 'un',
    defaultQuantity: 4,
    materialUnitCost: 195.0,
    laborUnitCost: 65.0,
    notes: 'Aro ajustável c/ vedante de borracha e montagem cuidada',
  },
  {
    id: 'car-02',
    category: 'Carpintarias e Caixilharias',
    description: 'Montagem de porta de correr embutida na parede (sistema tipo Scrigno/Ermetika)',
    unit: 'un',
    defaultQuantity: 1,
    materialUnitCost: 280.0,
    laborUnitCost: 95.0,
    notes: 'Inclui estrutura embutida e folha lacada',
  },
  {
    id: 'car-03',
    category: 'Carpintarias e Caixilharias',
    description: 'Fornecimento e aplicação de janela em PVC c/ perfil de 70mm, 5 câmaras, vidro duplo térmico e estores elétricos térmicos',
    unit: 'm²',
    defaultQuantity: 6,
    materialUnitCost: 240.0,
    laborUnitCost: 45.0,
    notes: 'Excelente isolamento térmico e acústico (classe A+)',
  },
  {
    id: 'car-04',
    category: 'Carpintarias e Caixilharias',
    description: 'Porta de entrada blindada de alta segurança c/ fechadura multipontos, aro em aço e painéis decorativos',
    unit: 'un',
    defaultQuantity: 1,
    materialUnitCost: 650.0,
    laborUnitCost: 150.0,
    notes: 'Com cilindro europeu anti-gazua e 5 chaves de segurança',
  },

  // 9. Climatização e AVAC
  {
    id: 'cli-01',
    category: 'Climatização e AVAC',
    description: 'Pré-instalação de Ar Condicionado (tubagem frigorífica de cobre isolada + alimentação elétrica + esgoto condensados)',
    unit: 'un',
    defaultQuantity: 3,
    materialUnitCost: 55.0,
    laborUnitCost: 75.0,
    notes: 'Por cada unidade interior / máquina split',
  },
  {
    id: 'cli-02',
    category: 'Climatização e AVAC',
    description: 'Fornecimento e montagem de Ar Condicionado Mono-Split 9.000 ou 12.000 BTU Inverter A+++ c/ Wi-Fi',
    unit: 'un',
    defaultQuantity: 2,
    materialUnitCost: 480.0,
    laborUnitCost: 140.0,
    notes: 'Inclui suportes, amortecedores de vibração e vácuo',
  },
  {
    id: 'cli-03',
    category: 'Climatização e AVAC',
    description: 'Instalação de Bomba de Calor para Águas Quentes Sanitárias (AQS 200L) c/ ligações hidráulicas e elétricas',
    unit: 'un',
    defaultQuantity: 1,
    materialUnitCost: 1450.0,
    laborUnitCost: 280.0,
    notes: 'Alta eficiência energética (A+) para poupança até 70%',
  },

  // 10. Isolamentos e Impermeabilização
  {
    id: 'iso-01',
    category: 'Isolamentos e Impermeabilização',
    description: 'Impermeabilização de paredes e piso da zona de duche com argamassa bicomponente flexível e tela de reforço',
    unit: 'm²',
    defaultQuantity: 10,
    materialUnitCost: 16.0,
    laborUnitCost: 14.0,
    notes: 'Com fitas de vedação nas juntas e cantos',
  },
  {
    id: 'iso-02',
    category: 'Isolamentos e Impermeabilização',
    description: 'Sistema ETICS (Capoto) de 60mm em EPS c/ barramento armado com rede de fibra e acabamento acrílico colorido',
    unit: 'm²',
    defaultQuantity: 50,
    materialUnitCost: 26.0,
    laborUnitCost: 24.0,
    notes: 'Revestimento térmico pelo exterior',
  },
  {
    id: 'iso-03',
    category: 'Isolamentos e Impermeabilização',
    description: 'Impermeabilização de terraço / cobertura plana c/ tela asfáltica SBS dupla e proteção pesada',
    unit: 'm²',
    defaultQuantity: 30,
    materialUnitCost: 22.0,
    laborUnitCost: 18.0,
    notes: 'Inclui remates perimetrais e meias-canas',
  },

  // 11. Outros Trabalhos
  {
    id: 'out-01',
    category: 'Outros Trabalhos',
    description: 'Limpeza profunda de fim de obra c/ máquinas industriais e produtos desincrustantes',
    unit: 'vg',
    defaultQuantity: 1,
    materialUnitCost: 40.0,
    laborUnitCost: 160.0,
    notes: 'Entrega da obra limpa e pronta a habitar',
  },
  {
    id: 'out-02',
    category: 'Outros Trabalhos',
    description: 'Mão de obra de trolha / servente polivalente para trabalhos diversos não especificados',
    unit: 'hora',
    defaultQuantity: 16,
    materialUnitCost: 0,
    laborUnitCost: 20.0,
    notes: 'Valor hora homem para apoios ou alterações',
  }
];
